root_prefix = ""
DATASET_PATH_PREFIX = ""
MODEL_PATH_PREFIX = ""
MODEL_PATH = "Qwen/Qwen2.5-72B-Instruct"
DATASET_PATH = ""

DEFAULT_LEARNING_RATE_SFT = 5e-5
DEFAULT_LEARNING_RATE_GRPO = 5e-7
DEFAULT_BATCH_SIZE = 1
DEFAULT_GRADIENT_ACCUMULATION_STEPS = 8
DEFAULT_MAX_SEQ_LENGTH = 2048
DEFAULT_NUM_TRAIN_EPOCHS = 3

DEFAULT_K_SAMPLES = 4
DEFAULT_C_RETRIEVALS = 4
DEFAULT_BETA_KL = 0.01
DEFAULT_EPSILON_CLIP = 0.2
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TOP_P = 0.9
DEFAULT_REWARD_CLIP = 5.0
DEFAULT_CACHE_SIMILARITY_THRESHOLD = 0.95
DEFAULT_EVIDENCE_SAMPLE_RATIO = 0.8

RETRIEVAL_TOP_K = 10
BOCHA_API_KEY = ""
OPENAI_API_KEY = ""
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100
SIMILARITY_THRESHOLD = 0.5

